name: Update Max Date

on:
  schedule:
    - cron: '10 0 * * *'  # Runs at 12:10 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update maxDate
        run: |
          # Use sed to find and increment the maxDate in script.js
          sed -i "s/const maxDate = new Date(Date.UTC(2024, 9, 10));/const maxDate = new Date(Date.UTC(2024, 9, $(date -d 'tomorrow' +'%d')));/" script.js
          
          # Verify the changes
          git diff

      - name: Commit and push changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add script.js
          git commit -m 'Update maxDate to the next day'
          git push
