name: Update Max Date

on:
  schedule:
    - cron: '10 0 * * *'  # Runs at 12:10 AM UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract and increment maxDate
        id: update_date
        run: |
          # Extract the current maxDate value from script.js
          max_date=$(grep -oP '(?<=const maxDate = new Date\(Date.UTC\(\d{4}, \d{1,2}, )\d{1,2}(?=\)\);)' script.js)
          
          # Extract year, month, and day from max_date
          year=$(echo $max_date | awk -F'[(),]' '{print $2}')
          month=$(echo $max_date | awk -F'[(),]' '{print $3}')
          day=$(echo $max_date | awk -F'[(),]' '{print $4}')
          
          # Increment the date by one day
          new_date=$(date -d "$year-$month-$day +1 day" +'%d')
          new_year=$(date -d "$year-$month-$day +1 day" +'%Y')
          new_month=$(date -d "$year-$month-$day +1 day" +'%m')
          
          # Update script.js with the new maxDate value
          sed -i "s/const maxDate = new Date(Date.UTC($year, $month-1, $day));/const maxDate = new Date(Date.UTC($new_year, $new_month-1, $new_date));/" script.js
          
          # Verify the changes
          git diff

      - name: Commit and push changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add script.js
          git commit -m 'Update maxDate to the next day'
          git push
