name: Update Max Date

on:
  schedule:
    # Runs every day at 7:07 AM UTC (which is midnight Central Time)
    - cron: '7 6 * * *'

jobs:
  update_maxdate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Adjust to the version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install any required Python packages

    - name: Run update script
      run: |
        python update_maxdate.py

    - name: Commit updated script.js
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add script.js
        git commit -m 'Update maxDate in script.js'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
