# update_dates.yml
#
#   - Action called to run update_dates.py
#
#

name: Update Dates

on:
  schedule:
    - cron: '10 6 * * *' # Runs everyday at 12:10 CDT
  workflow_dispatch: # Manual Trigger

jobs:
  update_dates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run update script
        run: python update_dates.py

      - name: Configure git
        run: |
          git config --global user.name 'Michael Lane'
          git config --global user.email 'michaellane2828@gmail.com'

      - name: Commit and push changes
        run: |
          git add script.js
          git commit -m "Update maxDate and currentDate in script.js"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}