name: Update Schedule

on:
  schedule:
    - cron: '0 6 * * *' # Runs at midnight every day (CST)
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  update_schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.12' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium openpyxl # Added openpyxl

      - name: Run script
        run: |
          python get_games_for_day.py